version: '3'

#  run development indexer
services:
  indexer:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: 'npm run dev'
    env_file:
      - .env
      - .env.local
    ports:
      - '8000:8000'
